### ISSUE TITLE
Endpoint Solicitar Microcrédito v2.0

### ISSUE THREAD

**Issue by damianfanaro** [IgrowkerTraining/i003-nativo-back#10]
URL: [http://localhost:8080/api/microcreditos/solicitar]( http://localhost:8080/api/microcreditos/solicitar)
action: POST
jwt: Si

Example body:
```
{  
    "title": "user1",
    "description": "user1",
    "amount": 100000,
}
```

Expected response:
```
{
    "id": "fbf12cb3-2832-48ec-aa36-5a22a6a8e299",
    "amount": 300000,
    "amountFinal": 330000,
    "remainingAmount": 300000,
    "createdDate": "2024-10-01",
    "expirationDate": "2024-10-31",
    "title": "Testing",
    "description": "Test1",
    "installmentCount": 1,
    "interestRate": 10,
    "transactionStatus": "PENDING"
}
```

**Notas:**
- Todos los campos son obligatorios, excepto la descripción.
- El usuario que solicita el microcrédito tiene que estar logueado.
- No se puede solicitar un microcrédito si el usuario que lo solicita  tiene alguno en estado ACCEPTED, PENDING,  DENIED o EXPIRED
- El monto (amount) que puede solicitar no debe superar el límite de $500.000 ni debe ser menor a cero (0).
- Se enviará una notificación informando que se creo el microcrédito
- Mensajes de error:
-- "Presenta un microcrédito pendiente."  (Transaction PENDING)
-- "Presenta un microcrédito vencido."  (Transaction EXPIRED)
-- "Ya tiene un microcrédito activo." (Transaction ACCEPTED)
-- "No puede solicitar un nuevo microcrédito. Debe regularizar el estado de su cuenta." (Transaction DENIED )
-- "El monto del microcrédito tiene que ser igual o menor a: $ 500000"

**Notas de cambios:**
- expirationDate esta seteada a los 30 días de la creación (se genera automáticamente) 
- InterestRate esta seteado al 10%. Es la tasa solidaria. El solicitante debe devolver al contribuyente el monto contribuido + el interés 
- installmentCount esta seteado en 1. Son las cuotas (actualmente 1 sola cuota) 
- amountFinal. Cálculo estimativo de lo que debería devolver en caso que consiguiera el total del monto pedido

**Comment by EmiiFernandez** [comment]
URL: [http://localhost:8080/api/microcreditos/solicitar]( http://localhost:8080/api/microcreditos/solicitar)
action: POST
jwt: Si

Example body:
```
{  
    "title": "user1",
    "description": "user1",
    "amount": 100000,
    "expirationDate": "2024-09-20"
}
```

Expected response:
```
{
    "id": "8940cb28-6c13-4c14-968d-3d4645aa6f9b",
    "amount": 100000,
    "remainingAmount": 100000,
    "createdDate": "2024-09-19",
    "expirationDate": "2024-09-20",
    "title": "user1",
    "description": "user1",
    "transactionStatus": "PENDENT"
}
```

**Notas:**
- Todos los campos son obligatorios, excepto la descripción.
- El usuario que solicita el microcrédito tiene que estar logueado.
- No se puede solicitar un microcrédito si el usuario que lo solicita  tiene alguno en estado Pendiente,  Denegado o Vencido (no pagado en la fecha de vencimiento).
- El monto (amount) que puede solicitar no debe superar el límite de $500.000 (se puede modificar el límite -conversable-) ni debe ser menor a cero (0).
- Mensajes de error:
-- "Presenta un microcrédito pendiente."
-- "Presenta un microcrédito vencido."
-- "No puede solicitar un nuevo microcrédito. Debe regularizar el estado de su cuenta."
-- "El monto del microcrédito tiene que ser igual o menor a: $ 500000"

**Comment by Andrea-Laurino** [comment]
Los test pasaron bien, lo unico para comentar es que nos gustaría que como respuesta de error en vez de darnos un estado 403 FORBIDDEN, nos diera algo más detallado indicando si el amount está vacío o no es numérico.
