### ISSUE TITLE
Tests Payment controller & implementation (parte 2 de 2)

### ISSUE THREAD

**Issue by GuillermoDivan** [IgrowkerTraining/i003-nativo-back#110]

**Comment by mdev-repos** [comment]
Unit test for...
ProcessPaymentTest (Controller & Service) --> DONE
GetPaymentsBetweenDates (Controller & Service) --> DONE
GetPaymentsAsClient (Controller & Service) --> DONE
GetPaymentsAsSeller (Controller & Service) --> DONE
