### ISSUE TITLE
Cambio automático de estado de microcrédito

### ISSUE THREAD

**Issue by EmiiFernandez** [IgrowkerTraining/i003-nativo-back#133]
Endpoint: **CAMBIO DE ESTADO DE MICROCRÉDITO**
URL: No
action: Proceso automático programado

**Notas:**
- Se ejecuta diariamente a las 00:00 horas en la zona horaria de Argentina.
- Se encarga de cambiar el estado de la transacción (TransactionStatus) de microcréditos con estado PENDING y ACCEPTED cuya fecha de expiración es igual a la fecha actual, tienen contribuciones y no han sido pagos, por lo que cambia el estado a EXPIRED.
- En caso de estar en estado PENDING y no tiene contribuciones el estado pasa a COMPLETED y le envía una notificación al solicitante informandole que no tiene contribuciones en su microcrédito

**Comment by Andrea-Laurino** [comment]
test pasado!
