### ISSUE TITLE
Endpoint registro usuario

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-back#32]
URL: http://localhost:8080/api/autenticacion/registro
action: POST

Expected body:
{
    "email":"ejemplo@gmail.com",
    "password":"Abcd1234!",
    "dni":"22333444",
    "name":"Jane",
    "surname":"Doe",
    "phone":"12345678",
    "birthday":"2006-09-17"
}

Expected Response: 201 CREATED
{
    "id": "166d78f1-8882-4ee3-b9cb-19b77c6fd222",
    "dni": 22333444,
    "name": "Jane",
    "surname": "Doe",
    "accountId": null,
    "email": "ejemplo@gmail.com",
    "phone": "12345678",
    "birthday": "2006-09-17",
    "verificationCode": "217127"
}

Notas:
- Todos los campos son obligatorios.
- El email e DNI deben ser únicos, es decir no se puede registrar si ya existe en la base de datos. 
- La contraseña debe contener 1 mayúscula, 1 minúscula, 1 numero y un carácter especial.
- La fecha de nacimiento valida que sea mayor de 18 años. 
- No hace falta que prueben con emails reales porque la response te da el verification code

((testing edit del github projects, favor de ignorar esta línea))

**Comment by Andrea-Laurino** [comment]
Hola Chicos, ya realizamos el testeo de registro, encontramos unos bugs, le dejamos el link de la planilla de "Reporte de Bugs"  https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?usp=drive_link

Cuando los hayan resuelto les pedimos que nos avisen asi se puede retestear.

**Comment by sheidiz** [comment]
@Andrea-Laurino @elianaspaccavento Buenas! Ya están corregidos los bugs que reportaron, cualquier cosa me comentan si ven algún otro error.
