### ISSUE TITLE
Desarrollar controlador de microcréditos

### ISSUE THREAD

**Issue by damianfanaro** [IgrowkerTraining/i003-nativo-back#6]
Crear el controlador MicrocreditoController para gestionar las solicitudes y contribuciones a microcréditos entre los usuarios. Este controlador debe procesar la creación de solicitudes y las contribuciones de otros usuarios.

**MICROCRÉDITOS:**
[http://localhost:8080/api/microcreditos](http://localhost:8080/api/microcreditos/solicitar)

**CREAR MICROCRÉDITO:**
[http://localhost:8080/api/microcreditos/solicitar](http://localhost:8080/api/microcreditos/solicitar)

**CREAR CONTRIBUCIÓN:**
[http://localhost:8080/api/microcreditos/contribuir](http://localhost:8080/api/microcreditos/contribuir)

**PAGAR MICROCRÉDITO:**
[http://localhost:8080/api/microcreditos/pagar/{id}](http://localhost:8080/api/microcreditos/pagar/%7Bid)

**BUSCAR MICROCRÉDITO POR ID:** 
[http://localhost:8080/api/microcreditos/{id}](http://localhost:8080/api/microcreditos/%7Bid)

**LISTAR TODOS LOS MICROCRÉDITOS:** 
[http://localhost:8080/api/microcreditos](http://localhost:8080/api/microcreditos/solicitar)

**BUSCAR MICROCRÉDITOS DEL USUARIO LOGUEADO:**
[http://localhost:8080/api/microcreditos/estado/{status}](http://localhost:8080/api/microcreditos/historial-estados/%7Bstatus)

_**Nota: Donde dice {id} en la url, eso debe ser reemplazado por la id del microcrédito y en {status} por el estado de la transacción que se quiera consultar.**_

**Comment by EmiiFernandez** [comment]
**MICROCRÉDITOS:**
[http://localhost:8080/api/microcreditos](http://localhost:8080/api/microcreditos/solicitar)

**CREAR MICROCRÉDITO:**
[http://localhost:8080/api/microcreditos/solicitar](http://localhost:8080/api/microcreditos/solicitar)

**CREAR CONTRIBUCIÓN:**
[http://localhost:8080/api/microcreditos/contribuir](http://localhost:8080/api/microcreditos/contribuir)

**PAGAR MICROCRÉDITO:**
[http://localhost:8080/api/microcreditos/pagar/{id}](http://localhost:8080/api/microcreditos/pagar/%7Bid)

**BUSCAR MICROCRÉDITO POR ID:** 
[http://localhost:8080/api/microcreditos/{id}](http://localhost:8080/api/microcreditos/%7Bid)

**LISTAR TODOS LOS MICROCRÉDITOS:** 
[http://localhost:8080/api/microcreditos](http://localhost:8080/api/microcreditos/solicitar)

**BUSCAR MICROCRÉDITOS DEL USUARIO LOGUEADO:**
[http://localhost:8080/api/microcreditos/estado/{status}](http://localhost:8080/api/microcreditos/historial-estados/%7Bstatus)


_**Nota: Donde dice {id} en la url, eso debe ser reemplazado por la id del microcrédito y en {status} por el estado de la transacción que se quiera consultar.**_
