### ISSUE TITLE
Endpoint historial de pagos (parte 2 de 2)

### ISSUE THREAD

**Issue by GuillermoDivan** [IgrowkerTraining/i003-nativo-back#63]
4° Get all payments between dates.

5° Get all payments by account as client.

6° Get all payments by account as seller.

**Comment by mdev-repos** [comment]
Son 3 endpoints con que retornan (mediante action GET) el historial de pagos (y cobros) del usuario logueado (todos requieren el jwt del user dueño de la cuenta, el cual esta logueado y esta accediendo a los endpoints para consultar su historial)

En TODOS los casos, el resultado será una lista, por lo que, a menos que haya error (de autenticación, con la url / action, o de formato) la respuesta SIEMPRE será 200. En caso de no haber resultados, la lista volverá vacía.


Endpoints

4° Get all payments between dates --> El usuario ingresa 2 fechas, una inicial y una final. El sistema buscara todos los pagos (recibidos y efectuados) entre las 00.00.00 hs de la fecha inicial y las 23.59.59 hs de la fecha final.

  - url: https://i003-nativo-back-production.up.railway.app/api/pagos/entrefechas
      - Se envia el JWT y dos parametros (fromDate y toDate) de tipo String y con el formato "yyyy/mm/dd"

  - example result para (https://i003-nativo-back-production.up.railway.app/api/pagos/entrefechas?fromDate=2024-09-21&toDate=2024-09-24):

[
    {
        "id": "d58bf054-a8f1-48fa-8357-f1ffc2584e99",
        "senderName": "Cosme",
        "senderSurname": "Fulanito",
        "senderAccount": "30000001",
        "receiverName": "Cosme",
        "receiverSurname": "Fulanito",
        "receiverAccount": "30000000",
        "amount": 1.00,
        "description": "Prueba 1",
        "transactionDate": "2024-10-04T01:10:23.423929",
        "transactionStatus": "ACCEPTED"
    },
    {
        "id": "7qwbf054-a8f1-48fa-8357-f1ffc2584e00",
        "senderName": "Cosme",
        "senderSurname": "Fulanito",
        "senderAccount": "30000001",
        "receiverName": "Cosme",
        "receiverSurname": "Fulanito",
        "receiverAccount": "30000000",
        "amount": 9.00,
        "description": "Prueba 2",
        "transactionDate": "2024-10-04T03:10:23.423929",
        "transactionStatus": "ACCEPTED"
    }
]

5° Get all payments by account as client --> El sistema buscara todos los pagos efectuados por el usuario logueado (modo "cliente").

  - url: https://i003-nativo-back-production.up.railway.app/api/pagos/realizados
      - Se envia el JWT

  - example result:

[
    {
        "id": "428c820c-fc55-4129-8711-18f33a04708d",
        "senderAccount": "a8af4447-f37e-460a-b18e-ab396c682519",
        "receiverAccount": "08709c0c-94e0-4dc3-82c4-1e2d3acff1e2",
        "amount": 3600.00,
        "description": "Test 2",
        "transactionDate": "2024-09-22T12:58:54.117823",
        "transactionStatus": "ACCEPTED"
    }
]

6° Get all payments by account as seller.--> El sistema buscara todos los pagos recibidos por el usuario logueado (modo "comerciante")

  - url: https://i003-nativo-back-production.up.railway.app/api/pagos/recibidos
      - Se envia el JWT

  - example result:

[
    {
        "id": "8bfc4ca6-7e63-41bb-8c40-7cdd64bcbf24",
        "senderAccount": "08709c0c-94e0-4dc3-82c4-1e2d3acff1e2",
        "receiverAccount": "a8af4447-f37e-460a-b18e-ab396c682519",
        "amount": 2500.00,
        "description": "Test 1",
        "transactionDate": "2024-09-22T12:48:54.29621",
        "transactionStatus": "ACCEPTED"
    }
]
