### ISSUE TITLE
Endpoint crear donación

### ISSUE THREAD

**Issue by GuillermoDivan** [IgrowkerTraining/i003-nativo-back#77]
URL: 
action:
jwt: 
Expected body:

Expected response:

Notas:

**Comment by MarioJGC** [comment]
URL: http://localhost:8080/api/donaciones/crear-donacion
action: POST
jwt: Si

Expected body:
{
    "amount":100,
    "accountIdDonor" : "348ad942-10aa-42b8-8173-a763c8d9b7e3",
    "accountIdBeneficiary" : "218d6f62-d5cf-423d-a0ac-4df8d7f1d06c",
    "anonymousDonation" : false
}

Expected response when anonymousDonation is false:
{
    "id": "fc245ffa-e97a-4835-a0d2-5c1874253393",
    "amount": 100,
    "accountIdDonor": "348ad942-10aa-42b8-8173-a763c8d9b7e3",
    "accountIdBeneficiary": "218d6f62-d5cf-423d-a0ac-4df8d7f1d06c",
    "createdAt": "2024-09-21T09:28:53.5010329",
    "status": "PENDENT"
}

Expected response when anonymousDonation is true:
{
    "id": "e17efc6c-6d57-4542-8ac1-637251e7662b",
    "amount": 100,
    "accountIdDonor": "348ad942-10aa-42b8-8173-a763c8d9b7e3",
    "donorName": "Mario",
    "donorLastName": "Grande",
    "accountIdBeneficiary": "218d6f62-d5cf-423d-a0ac-4df8d7f1d06c",
    "beneficiaryName": "Ulises",
    "beneficiaryLastName": "Gonzales",
    "createdAt": "2024-09-21T09:33:09.17601",
    "status": "PENDENT"
}

Notas:

Todos los campos son obligatorios.
El usuario donador tiene que estar logueado en su cuenta.
El id de la respuesta corresponde a la donación creada.
El donador debe estar logueado y no puede ser el beneficiario.
El status siempre será "PENDENT" al crear una donación.

Mensaje de error:
-- Al crear una donación: "El id de la cuenta donante no existe" o "El id de la cuenta beneficiario no existe"
-- Al crear una donación se valida que la cuenta del donador tenga fondos suficientes: "Tu cuenta no tiene suficientes fondos."

**Comment by Andrea-Laurino** [comment]
Hola chicos!! encontre un bug que no da un mensaje claro en la respuesta, y guille me dijo que estaban trabajando en esto... 

https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997

cualquier cosa nos hablan!! saludos

**Comment by MarioJGC** [comment]
En el campo amount, no va a recibir ese tipo de dato en el monto, eso no se puede validar mediante un request, puesto que el valor del campo puede ser null o un string vacio(""). Se adjunta la validación correcta.

Solo puede ser uno de los siguientes casos:
![Image](https://github.com/user-attachments/assets/1b44607a-93bc-4f79-9cef-451309bc0276)
![Image](https://github.com/user-attachments/assets/1d1cbb0a-15fd-4bff-be0b-a713e61f901d)

**Comment by Andrea-Laurino** [comment]
perfecto! ahí entendimos que no es probable hacer una solicitud son monto alguno.
