### ISSUE TITLE
Endpoint confirmar donación

### ISSUE THREAD

**Issue by GuillermoDivan** [IgrowkerTraining/i003-nativo-back#78]

**Comment by UlisesGS** [comment]
URL: http://localhost:8080/api/donaciones/confirmar-donacion
action: POST
jwt: Si

Expected response when status is ACCEPTED:
{
"amount":100,
"accountIdDonor" : "348ad942-10aa-42b8-8173-a763c8d9b7e3",
"accountIdBeneficiary" : "218d6f62-d5cf-423d-a0ac-4df8d7f1d06c",
"status" : "ACCEPTED"
}

Expected response when status is DENIED:
{
"amount":100,
"accountIdDonor" : "348ad942-10aa-42b8-8173-a763c8d9b7e3",
"accountIdBeneficiary" : "218d6f62-d5cf-423d-a0ac-4df8d7f1d06c",
"status" : "DENIED"
}

Notas:

Todos los campos son obligatorios.
El usuario beneficiario tiene que estar logueado en su cuenta.
El id de la respuesta corresponde a la donación creada.
El beneficiario debe estar logueado.
El status de la donacion se puede aceptar o denegar.
ACCEPTED: si la donacion se acepta se saca el monto de la donacion en el reservedAmount y se le suma al beneficiario en su monto.
DENNIED: si la donacion se niega se saca el monto de la donacion en el reservedAmount, y se guarda como denegada.

Mensaje de error:
-- Primero que todo se valida si la donacion todavia sigue pendiente o ya se finalizo: "Esta donacion ya fue finalizada"
-- Al confirmar una donación: "El id de la donacion no existe" || "La cuenta del donador no existe")
-- Al confirmar la donacion se valida que la ceunta del beneficiario sea la que este confirmando: "La cuenta provista no fue encontrada."

**Comment by Andrea-Laurino** [comment]
hola chicos!! cuando aceptó la donación está perfecto pero cuando quiero denegarlo no me deja y me da un 403, esto logueada como el beneficiario de dicha donación. 

https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997

**Comment by UlisesGS** [comment]
Buenas andre!!, con mario estuvimos viendo y nos funciono correctamente. Vimos en la imagen que dejaron del postman que el DENIED, lo pusieron con doble n, capaz se dio por eso.


![Image](https://github.com/user-attachments/assets/96801af2-6497-4eb5-97ee-f1e21f224619)

--
Probando en postman este endpoint nos dimos cuenta que podias aceptar mas de una vez una confirmacion de donacion, y eso alteraba los montos jajaja. En un rato ya subimos el codigo limpio para que lo puedan probar y vamos a modificar el comentario de arriba con la nueva exception.

**Comment by Andrea-Laurino** [comment]
hola uli! claro ahí me dio bien, me guie por la data que pusieron mas arriba.
