### ISSUE TITLE
Endpoint contribuir a un microcrédito

### ISSUE THREAD

**Issue by GuillermoDivan** [IgrowkerTraining/i003-nativo-back#80]
Enpoint: **CONTRIBUIR A UN MICROCRÉDITO"**
URL: [http://localhost:8080/api/microcreditos/contribuir](http://localhost:8080/api/microcreditos/contribuir)
action: POST
jwt: Si

Expected body:
```
{
    "microcreditId": "8940cb28-6c13-4c14-968d-3d4645aa6f9b",
    "amount": 10000
}
```

Expected response:
```
{
    "id": "ad9092d4-53fe-46da-8665-6aa727d6b9f2",
    "lenderAccountId": "c2f99ca5-e6db-4e19-8baa-8cf8fa6ed958",
    "lenderFullname": "USER2, user2",
    "borrowerFullname": "USER1, user1",
    "microcreditId": "8940cb28-6c13-4c14-968d-3d4645aa6f9b",
    "amount": 10000,
    "createdDate": "2024-09-19",
    "expiredDateMicrocredit": "2024-09-20",
    "transactionStatus": "ACCEPTED"
}
```

**Notas:**

- El usuario debe estar logueado
- Todos los campos son obligatorios.
- El microcreditId hace referencia al id del microcrédito cuando está creado.
- El usuario contribuyente tiene que estar logueado en su cuenta.
- El usuario contribuyente no puede ser el mismo que solicitó el microcrédito.
- Tiene que colocar un microcreditId que exista. 
- Tiene que tener fondos suficientes para realizar la contribución
- Se envía una notificación por mail de la contribución al solicitante del microcrédito
- Mensaje de error: 
-- Al buscar el microcrédito: "Microcrédito no encontrado"
-- Al verificar que la cuenta del contribuyente tenga el saldo que quiere contribuir: "Fondos insuficientes"

**Comment by EmiiFernandez** [comment]
URL: [http://localhost:8080/api/microcreditos/contribuir](http://localhost:8080/api/microcreditos/contribuir)
action: POST
jwt: Si

Expected body:
```
{
    "microcreditId": "8940cb28-6c13-4c14-968d-3d4645aa6f9b",
    "amount": 10000
}
```

Expected response:
```
{
    "id": "ad9092d4-53fe-46da-8665-6aa727d6b9f2",
    "lenderAccountId": "c2f99ca5-e6db-4e19-8baa-8cf8fa6ed958",
    "lenderFullname": "USER2, user2",
    "borrowerFullname": "USER1, user1",
    "microcreditId": "8940cb28-6c13-4c14-968d-3d4645aa6f9b",
    "amount": 10000,
    "createdDate": "2024-09-19",
    "expiredDateMicrocredit": "2024-09-20",
    "transactionStatus": "ACCEPTED"
}
```

Notas:

- Todos los campos son obligatorios.
- El microcreditId hace referencia al id del microcrédito cuando está creado.
- El usuario contribuyente tiene que estar logueado en su cuenta.
- El usuario contribuyente no puede ser el mismo que solicitó el microcrédito.
- Tiene que colocar un microcreditId que exista. 
- Mensaje de error: 
-- Al buscar el microcrédito: "Microcrédito no encontrado"
-- Al verificar que la cuenta del contribuyente tenga el saldo que quiere contribuir: "Fondos insuficientes"

**Comment by Andrea-Laurino** [comment]
hola chicas!!! este no le hice comentario pero en la planilla de bug esta informado.

https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997

**Comment by EmiiFernandez** [comment]
**BUG09 | CONTRIBUCION A MICROCREDITOS COMPLETO | Se intento contribuir a un microcrédito ya completo, da como estado 403 y no se ha obtenido respuesta con ningún mensaje detallado**
 

-  Se realizo el cambio donde solo se puede contribuir en un microcrédito con estado PENDING.
- No se puede contribuir en microcréditos con estado: ACCEPTED  (alcanzo el monto total), COMPLETED (se encuentra pago), EXPIRED (vencido)
- Se agrego que si el contribuidor tiene un microcrédito en estado EXPIRED (vencido) no pueda contribuir en otro microcrédito

**Comment by Andrea-Laurino** [comment]
Perfecto! Paso correctamente!
