### ISSUE TITLE
Endpoint login usuario

### ISSUE THREAD

**Issue by GuillermoDivan** [IgrowkerTraining/i003-nativo-back#83]
URL: http://localhost:8080/api/autenticacion/inicio-sesion
action: POST

Expected body:
{
    "email":"ejemplo@gmail.com",
    "password":"Abcd1234!"
}

Expected response: 200 OK
{
    "id": "166d78f1-8882-4ee3-b9cb-19b77c6fd222",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlamVtcGxvQGdtYWlsLmNvbSIsImlhdCI6MTcyNjc5NjkwNywiZXhwIjoxNzI2ODAwNTA3fQ.azhpaICi3lD1XtaYsOJMj1j6sqWIaxBT3A46WCoX8LY",
    "expiresIn": 3600000
}

Notas:
- Nos regresara 404 si el usuario no existe.
- Nos regresara 401 si el usuario existe pero no verifico su cuenta o si la contraseña no es correcta.

**Comment by Andrea-Laurino** [comment]
Hola Chicos! este tickets está probado cuando pueda lo paso para DONE, hasta ahora no puedo...
