### ISSUE TITLE
Endpoint editar usuario

### ISSUE THREAD

**Issue by GuillermoDivan** [IgrowkerTraining/i003-nativo-back#85]
URL: 
action:
jwt: 
Expected body:
Expected response:
Notas:

**Comment by MircoSantoni** [comment]
URL: http://localhost:8080/api/usuarios/editar-usuario
action: POST
jwt: Debe ser del usuario que quiere modificar sus datos

Expected body: 
{
    "id": "9e76218e-0a99-4c34-a6a1-7ddef8686167",
    "phone": 12345678,
    "name": "Jhon",
    "surname": "Doe"
}

Expected response: 200 OK
{
    "phone": "12345678",
    "name": "Jhon",
    "surname": "Doe"
}



URL: http://localhost:8080/api/usuarios/editar-correo
action: POST
jwt: Debe ser del usuario que quiere modificar sus datos
Expected body: 
{
    "id": "9e76218e-0a99-4c34-a6a1-7ddef8686167",
    "email": "jhonDoe@Gmail.com"
}
Expected response: 200 OK
{
    "email": "jhonDoe@Gmail.com"
}
Notas:

-  Se pueden modificar cualquiera de los distintos atributos, son opcionales
-  Al cambiar el correo, deberemos volver a iniciar sesion
